name: bitehub
description: BiteHub - Homemade Food Delivery Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^5.4.0

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^13.2.0

  # Storage
  shared_preferences: ^2.2.3

  # Images
  cached_network_image: ^3.3.1

  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
